### ISSUE TITLE
Custom element doesn't exist light-entity-row

### ISSUE THREAD

**Issue by carlba** [custom-cards/light-entity-row#2]
I have added the following section 

```yaml
      - type: entities
        title: Lights
        entities:
          - type: "custom:light-entity-row"
            entity: light.kitchen_table
            icon: mdi:lamp  # optional
            name: Lamp      # optional
          - type: "custom:light-entity-row"
            entity: light.kitchen_fan
            showColorPicker: true # shows color picker if supported
            showColorSliders: true # shows hue/saturation sliders if supported
```

And I get this

![image](https://user-images.githubusercontent.com/1884191/48319158-9cd3fc80-e60a-11e8-96c5-55693f23f17f.png)

![image](https://user-images.githubusercontent.com/1884191/48319170-c9881400-e60a-11e8-8c22-c8e871424007.png)

**Comment by carlba** [comment]
Stupid me forgot to add

```yaml
resources:
  - url: /local/light-entity-row.js?v=0.2.4
    type: js
```

It would be nice if the documentation had a note about it though it is easy to miss :)
