### ISSUE TITLE
Card is displayed only as a popup

### ISSUE THREAD

**Issue by DominikPalo** [custom-cards/light-entity-row#4]
I've added a light-entity-row for my Yeelight LED strip. But in the main UI, it's displayed as a error "Custom element doesn't exist" and the actual card popups after clicking on that error.

![image](https://user-images.githubusercontent.com/1623257/52182824-6d93ec80-2801-11e9-8e1d-0c2400984db0.png)

My config:
```
title: LED strip
type: entities
entities:
  - type: 'custom:light-entity-row'
    entity: light.yeelight_strip2_04cf8c777dc8
    showColorPicker: true
    showColorSliders: true
```

Home Assistant version: 0.86.4
